# Use Node.js LTS version as the base image
FROM node:lts-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to container
#COPY package*.json ./

# Install dependencies
#RUN npm install

# Copy the rest of the application code to the container
#COPY . .

# Build the application
RUN npm run build

# Install a simple HTTP server to serve the application
RUN npm install -g serve

# Expose port 9400
EXPOSE 9400

# Command to run the Next.js application
#CMD ["npm", "run", "dev"]


# Command to run the application
CMD ["serve", "-s", "dist", "-l", "9400"]
